[versions]
agp = "9.3.0"
junit = "4.13.2"
robolectric = "4.17"
bouncycastle = "1.79"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
bouncycastle = { group = "org.bouncycastle", name = "bcprov-jdk15to18", version.ref = "bouncycastle" }
bctls = { group = "org.bouncycastle", name = "bctls-jdk15to18", version.ref = "bouncycastle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
